version: '3.3'
services:
  db:
    image: mysql:8.0.22
    container_name: devices_services
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'devices_services'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'devices_services_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db_d:/var/lib/mysql
# Names our volume
volumes:
  db_d:
